/**
 * Site configuration: what it must look like, and what happens when it is checked against the
 * page it claims to describe.
 *
 * A configuration is **data the plugin interprets**, never code it runs. Every locator is a
 * closed set of predicates (see docs/SITE_CONFIG_SPEC.md), so three things follow, and all
 * three are enforced here rather than assumed:
 *
 * - An unknown key is rejected. That is what makes "no raw CSS", "no stored ref" and "no
 *   agent-authored JavaScript" properties of the format instead of promises in a document.
 * - A locator that does not resolve to exactly one element inside a card **refuses that
 *   card's action** instead of falling back to the first match. A wrong greeting cannot be
 *   taken back, so "close enough" is not a tolerable resolution.
 * - A configuration carries `markers`: conditions that must hold for it to apply at all. When
 *   one fails the answer is `needs_adaptation` with the failing marker named, never a
 *   best-effort guess at what moved.
 *
 * The consequence gate is deliberately absent from the format. A configuration may declare
 * `effect: "quota"` to escalate an action into the confirmation gate, but declaring
 * `"none"` cannot release it: that decision is made from what the plugin can observe, in
 * `lib/pacing.js` and `lib/act.js`.
 *
 * @module @local/dsh-jev-browser/lib/site
 */

import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { localDir } from './local.js';
import { evaluate } from './page.js';

/** Keys a configuration may carry at the top level. Anything else is a mistake. */
export const CONFIG_KEYS = ['version', 'domain', 'page', 'markers', 'cards', 'fields', 'actions', 'validated'];

/** Keys a locator may carry. `ref` is absent on purpose: a ref addresses one snapshot only. */
export const LOCATOR_KEYS = ['tag', 'role', 'text', 'attr', 'href', 'nth', 'within'];

/** Keys a text condition may carry. */
export const TEXT_KEYS = ['equals', 'contains', 'matches'];

/** The closed action vocabulary, and the effects a configuration may declare. */
export const ACTION_TYPES = ['read', 'click', 'type', 'select', 'scroll', 'wait'];
export const EFFECTS = ['none', 'navigation', 'quota'];

/** Markers a configuration can require before it is allowed to apply. */
export const MARKER_KINDS = ['exists', 'text'];

/** The hit rate below which a configuration may be read but must not send. */
export const USABLE_HIT_RATE = 0.9;

/**
 * A token carrying four consecutive digits, or a hex-ish suffix, is generated by the site's
 * build and changes on every deploy. Anchoring on one is how a learned configuration dies
 * quietly, so it is reported rather than silently tolerated.
 */
const GENERATED = /(?:\d{4,}|[_\-][0-9a-f]{6,}|[0-9a-f]{8,})/i;

function fail(path, message) {
  throw new Error(`invalid site configuration at ${path}: ${message}`);
}

function isRecord(value) {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function checkTextCondition(value, path) {
  if (!isRecord(value)) fail(path, 'must be an object');
  const keys = Object.keys(value);
  if (keys.length === 0) fail(path, `must carry one of ${TEXT_KEYS.join(', ')}`);
  for (const key of keys) {
    if (!TEXT_KEYS.includes(key)) fail(`${path}.${key}`, `unknown condition; expected one of ${TEXT_KEYS.join(', ')}`);
    if (typeof value[key] !== 'string' || value[key] === '') fail(`${path}.${key}`, 'must be a non-empty string');
    if (key === 'matches') {
      try {
        new RegExp(value[key]);
      } catch {
        fail(`${path}.matches`, 'is not a valid regular expression');
      }
    }
  }
}

function checkLocator(locator, path) {
  if (!isRecord(locator)) fail(path, 'must be an object');
  if (Object.keys(locator).length === 0) fail(path, 'must carry at least one condition');
  for (const [key, value] of Object.entries(locator)) {
    if (!LOCATOR_KEYS.includes(key)) {
      fail(`${path}.${key}`, `unknown key; expected one of ${LOCATOR_KEYS.join(', ')}`);
    }
    if (key === 'tag' || key === 'role') {
      if (typeof value !== 'string' || value === '') fail(`${path}.${key}`, 'must be a non-empty string');
    } else if (key === 'text' || key === 'href') {
      checkTextCondition(value, `${path}.${key}`);
    } else if (key === 'nth') {
      if (!Number.isInteger(value) || value < 0) fail(`${path}.nth`, 'must be a non-negative integer');
    } else if (key === 'attr') {
      if (!Array.isArray(value) || value.length === 0) fail(`${path}.attr`, 'must be a non-empty array');
      value.forEach((entry, i) => {
        if (!isRecord(entry) || typeof entry.name !== 'string' || entry.name === '') {
          fail(`${path}.attr[${i}]`, 'must be an object with a non-empty name');
        }
        const conditions = Object.keys(entry).filter((k) => k !== 'name');
        if (conditions.length === 0) fail(`${path}.attr[${i}]`, 'must carry a condition');
        for (const condition of conditions) {
          if (!TEXT_KEYS.includes(condition)) fail(`${path}.attr[${i}].${condition}`, `expected one of ${TEXT_KEYS.join(', ')}`);
        }
      });
    } else if (key === 'within') {
      checkLocator(value, `${path}.within`);
    }
  }
}

/**
 * Validate a configuration, or explain precisely why it is not one.
 *
 * @throws with a path and a reason. A caller that has just had a configuration generated for
 *   it needs to know which line to fix, not that something was wrong somewhere.
 */
export function validateConfig(config) {
  if (!isRecord(config)) fail('<root>', 'must be an object');
  for (const key of Object.keys(config)) {
    if (!CONFIG_KEYS.includes(key)) fail(key, `unknown key; expected one of ${CONFIG_KEYS.join(', ')}`);
  }
  if (!Number.isInteger(config.version) || config.version < 1) fail('version', 'must be a positive integer');
  for (const key of ['domain', 'page']) {
    if (typeof config[key] !== 'string' || config[key].trim() === '') fail(key, 'must be a non-empty string');
  }
  if (!isRecord(config.cards)) fail('cards', 'must be an object');
  checkLocator(config.cards.locator, 'cards.locator');
  if (config.cards.sample !== undefined && (!Number.isInteger(config.cards.sample) || config.cards.sample < 1)) {
    fail('cards.sample', 'must be a positive integer');
  }
  if (config.cards.identity !== undefined) {
    if (!isRecord(config.cards.identity) || typeof config.cards.identity.from !== 'string') {
      fail('cards.identity', 'must be an object with a `from`');
    }
    const from = config.cards.identity.from;
    if (from !== 'href' && from !== 'text' && !from.startsWith('attr:')) {
      fail('cards.identity.from', 'must be "href", "text", or "attr:<name>"');
    }
    if (from.startsWith('attr:') && from.slice(5) === '') fail('cards.identity.from', 'names no attribute after "attr:"');
    if (config.cards.identity.matches !== undefined) {
      try {
        new RegExp(config.cards.identity.matches);
      } catch {
        fail('cards.identity.matches', 'is not a valid regular expression');
      }
    }
  }
  if (config.fields !== undefined) {
    if (!isRecord(config.fields)) fail('fields', 'must be an object');
    for (const [name, field] of Object.entries(config.fields)) {
      if (!isRecord(field)) fail(`fields.${name}`, 'must be an object');
      checkLocator(field.locator, `fields.${name}.locator`);
    }
  }
  if (config.actions === undefined || Object.keys(config.actions).length === 0) {
    fail('actions', 'must define at least one action');
  }
  if (!isRecord(config.actions)) fail('actions', 'must be an object');
  for (const [name, action] of Object.entries(config.actions)) {
    if (!isRecord(action)) fail(`actions.${name}`, 'must be an object');
    if (action.scope !== 'card' && action.scope !== 'page') fail(`actions.${name}.scope`, 'must be "card" or "page"');
    if (!ACTION_TYPES.includes(action.type)) fail(`actions.${name}.type`, `must be one of ${ACTION_TYPES.join(', ')}`);
    if (action.effect !== undefined && !EFFECTS.includes(action.effect)) {
      fail(`actions.${name}.effect`, `must be one of ${EFFECTS.join(', ')}`);
    }
    checkLocator(action.locator, `actions.${name}.locator`);
  }
  if (config.markers !== undefined) {
    if (!Array.isArray(config.markers)) fail('markers', 'must be an array');
    config.markers.forEach((marker, i) => {
      if (!isRecord(marker) || !MARKER_KINDS.includes(marker.kind)) {
        fail(`markers[${i}].kind`, `must be one of ${MARKER_KINDS.join(', ')}`);
      }
      checkLocator(marker.locator, `markers[${i}].locator`);
      if (marker.contains !== undefined && typeof marker.contains !== 'string') fail(`markers[${i}].contains`, 'must be a string');
    });
  }
  return config;
}

/** A file name for one configuration, derived from what it describes. */
export function configFileName(config) {
  // Dots become separators too: keeping them let a domain of `../../etc` produce a name
  // containing `..`, which is a question nobody should have to reason about later.
  const slug = (value) => String(value).toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 60) || 'unnamed';
  return `${slug(config.domain)}--${slug(config.page)}.json`;
}

/**
 * Read a saved configuration.
 *
 * @returns the configuration, or `null` when none is saved. A malformed file throws rather
 *   than being ignored: silently re-learning a site because its saved rules went bad is how
 *   a working configuration appears to stop working for no reason.
 */
export async function loadConfig(config) {
  const path = join(localDir('sites'), configFileName(config));
  const raw = await readFile(path, 'utf8').catch(() => null);
  if (raw === null) return null;
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch (error) {
    throw new Error(`the saved site configuration at ${path} is not valid JSON: ${error.message}`);
  }
  return validateConfig(parsed);
}

/** Write a configuration, validated first, atomically. */
export async function saveConfig(config) {
  validateConfig(config);
  const directory = localDir('sites');
  await mkdir(directory, { recursive: true });
  const path = join(directory, configFileName(config));
  const temporary = `${path}.${process.pid}.tmp`;
  await writeFile(temporary, `${JSON.stringify(config, null, 2)}\n`, 'utf8');
  await rename(temporary, path);
  return path;
}

/**
 * Check a configuration against the page it is open on.
 *
 * @returns the report the spec's §7 describes, plus `canSend`, so no caller has to re-derive
 *   the threshold and get it slightly different.
 */
export async function check(cdp, sessionId, { config, limit = 20 } = {}) {
  validateConfig(config);
  const expression = `(${resolveImpl.toString()})(${JSON.stringify(config)},${JSON.stringify(limit)})`;
  const raw = await evaluate(cdp, sessionId, expression, { timeoutMs: 30000 });
  if (!raw || typeof raw !== 'object') throw new Error('the page returned no resolution result');

  const cards = Array.isArray(raw.cards) ? raw.cards : [];
  const fieldNames = Object.keys(config.fields ?? {});
  const cardActions = Object.entries(config.actions).filter(([, action]) => action.scope === 'card');
  let missing = 0;
  let ambiguous = 0;
  for (const card of cards) {
    for (const name of fieldNames) if (card.fields?.[name]?.ok !== true) missing += 1;
    // A card, not a (card, action) pair: the report answers "how many records are unsafe to
    // act on", and one card with two unresolvable actions is still one card.
    const unsettled = cardActions.some(([actionName]) => {
      const hits = card.actions?.[actionName]?.matches;
      return !Array.isArray(hits) || hits.length !== 1;
    });
    if (unsettled) ambiguous += 1;
  }
  const fieldSlots = cards.length * fieldNames.length;
  const hitRate = fieldSlots === 0 ? (cards.length > 0 ? 1 : 0) : (fieldSlots - missing) / fieldSlots;
  const markerFailures = Array.isArray(raw.markerFailures) ? raw.markerFailures : [];
  const unstableConditions = Array.isArray(raw.unstableConditions) ? raw.unstableConditions : [];

  let verdict = 'usable';
  if (markerFailures.length > 0 || cards.length === 0) verdict = 'stale';
  else if (hitRate < USABLE_HIT_RATE || ambiguous > 0) verdict = 'degraded';

  return {
    url: String(raw.url ?? ''),
    title: String(raw.title ?? ''),
    matched: cards.length,
    ambiguous,
    missing,
    hitRate,
    unstableConditions,
    markerFailures,
    verdict,
    // The threshold lives in one place: hitRate, no ambiguity, and the markers holding.
    canSend: verdict === 'usable',
    cards: cards.slice(0, limit).map((card) => ({
      identity: String(card.identity ?? ''),
      text: String(card.text ?? ''),
      fields: card.fields ?? {},
      actions: card.actions ?? {},
    })),
  };
}

/**
 * Read the records off the page using a configuration that already resolved.
 *
 * This is the read half of "code reads, the model judges": the layout work is done by the
 * configuration, so nothing has to be located per record and no model decides where the name
 * is. It returns facts **with their provenance**: each field carries whether it was found, so
 * a caller can mark a missing one as unknown instead of inventing it, which is the rule the
 * whole recruiting flow depends on.
 *
 * It reads at `degraded` as well as at `usable` — a configuration that cannot send can still
 * be worth looking through, and the report says which it is. A `stale` one yields no cards at
 * all, because its markers did not hold and its matches would mean nothing.
 *
 * @returns the report plus the records it resolved.
 */
export async function readCandidates(cdp, sessionId, { config, limit = 50 } = {}) {
  const report = await check(cdp, sessionId, { config, limit });
  const candidates = report.cards.map((card) => {
    const fields = {};
    for (const [name, field] of Object.entries(card.fields)) {
      fields[name] = field.ok === true ? field.value : null;
    }
    const actions = {};
    for (const [name, action] of Object.entries(card.actions)) {
      actions[name] = Array.isArray(action.matches) && action.matches.length === 1;
    }
    return {
      // An identity is what deduplication keys on, so an unresolved one is reported as empty
      // and a caller must refuse to deduplicate rather than fall back to a name.
      identity: card.identity,
      text: card.text,
      fields,
      actions,
      unknown: Object.entries(fields).filter(([, value]) => value === null).map(([name]) => name),
    };
  });
  return {
    url: report.url,
    title: report.title,
    count: candidates.length,
    candidates,
    verdict: report.verdict,
    canSend: report.canSend,
    markerFailures: report.markerFailures,
    unstableConditions: report.unstableConditions,
    hitRate: report.hitRate,
    ambiguous: report.ambiguous,
  };
}

/**
 * The page-side half of {@link check}.
 *
 * One evaluation resolves everything, because the card elements never leave the page: passing
 * them out and back would make every locator depend on a stale handle, which is the mistake
 * this whole format exists to avoid.
 */
function resolveImpl(config, sampleLimit) {
  var GENERATED = /(?:\d{4,}|[_\-][0-9a-f]{6,}|[0-9a-f]{8,})/i;
  var unstableConditions = [];
  var unstableSeen = {};

  function noteUnstable(path, element) {
    var text = String((element && element.className) || '');
    if (!GENERATED.test(text)) return;
    if (unstableSeen[path]) return;
    unstableSeen[path] = true;
    unstableConditions.push(path);
  }

  function normalizedText(element) {
    var text = '';
    try { text = String(element.innerText || element.textContent || ''); } catch (e) { text = ''; }
    return text.replace(/\s+/g, ' ').trim();
  }

  function roleOf(element) {
    var explicit = element.getAttribute ? element.getAttribute('role') : '';
    if (explicit) return explicit;
    var tag = element.tagName.toLowerCase();
    if (tag === 'a') return element.hasAttribute('href') ? 'link' : '';
    if (tag === 'button') return 'button';
    if (tag === 'input') return String(element.getAttribute('type') || 'text').toLowerCase();
    if (tag === 'select') return 'combobox';
    if (tag === 'textarea') return 'textbox';
    return '';
  }

  function conditionHolds(value, condition, path, element) {
    for (var key in condition) {
      if (!Object.prototype.hasOwnProperty.call(condition, key)) continue;
      var want = condition[key];
      if (key === 'equals') { if (value !== want) return false; }
      else if (key === 'contains') { if (value.indexOf(want) === -1) return false; }
      else if (key === 'matches') { if (!new RegExp(want).test(value)) return false; }
    }
    return true;
  }

  function matches(element, locator, path) {
    if (locator.tag && element.tagName.toLowerCase() !== String(locator.tag).toLowerCase()) return false;
    if (locator.role && roleOf(element) !== locator.role) return false;
    if (locator.text && !conditionHolds(normalizedText(element), locator.text, path, element)) return false;
    if (locator.href && !conditionHolds(String(element.getAttribute('href') || ''), locator.href, path, element)) return false;
    if (locator.attr) {
      for (var i = 0; i < locator.attr.length; i++) {
        var entry = locator.attr[i];
        var actual = String(element.getAttribute(entry.name) || '');
        if (entry.name === 'class') noteUnstable(path + '.attr[class]', element);
        var condition = {};
        for (var k in entry) if (k !== 'name') condition[k] = entry[k];
        if (!conditionHolds(actual, condition, path, element)) return false;
      }
    }
    return true;
  }

  function selectWithin(scope, locator, path, out) {
    var all = scope.querySelectorAll('*');
    for (var i = 0; i < all.length; i++) if (matches(all[i], locator, path)) out.push(all[i]);
    return out;
  }

  function select(locator, path) {
    var found = [];
    if (locator.within) {
      var parents = select(locator.within, path + '.within');
      var outer = {};
      for (var k in locator) if (k !== 'within') outer[k] = locator[k];
      for (var p = 0; p < parents.length; p++) selectWithin(parents[p], outer, path, found);
    } else {
      selectWithin(document, locator, path, found);
    }
    // Nested `within` matches can reach the same descendant twice, which would make `nth`
    // pick the wrong element and inflate every count.
    var unique = [];
    for (var u = 0; u < found.length; u++) if (unique.indexOf(found[u]) === -1) unique.push(found[u]);
    if (typeof locator.nth === 'number') return unique.length > locator.nth ? [unique[locator.nth]] : [];
    return unique;
  }

  var markerFailures = [];
  var markers = config.markers || [];
  for (var m = 0; m < markers.length; m++) {
    var marker = markers[m];
    var markerPath = 'markers[' + m + ']';
    var hits = select(marker.locator, markerPath);
    if (marker.kind === 'exists') {
      if (hits.length === 0) markerFailures.push(markerPath + ' (exists)');
    } else if (marker.kind === 'text') {
      var found = false;
      for (var h = 0; h < hits.length; h++) {
        if (normalizedText(hits[h]).indexOf(String(marker.contains || '')) !== -1) { found = true; break; }
      }
      if (!found) markerFailures.push(markerPath + ' (text ' + JSON.stringify(marker.contains || '') + ')');
    }
  }

  var cardElements = markerFailures.length > 0 ? [] : select(config.cards.locator, 'cards.locator');
  var fieldNames = config.fields ? Object.keys(config.fields) : [];
  var actionNames = config.actions ? Object.keys(config.actions) : [];
  var cards = [];
  for (var c = 0; c < cardElements.length; c++) {
    var element = cardElements[c];
    var identity = '';
    if (config.cards.identity) {
      var from = config.cards.identity.from;
      var source = from.indexOf('attr:') === 0
        ? String(element.getAttribute(from.slice(5)) || '')
        : from === 'href' ? String(element.getAttribute('href') || '') : normalizedText(element);
      if (config.cards.identity.matches) {
        var match = new RegExp(config.cards.identity.matches).exec(source);
        if (match) identity = match[1] !== undefined ? match[1] : match[0];
      } else identity = source.slice(0, 120);
    }
    var fields = {};
    for (var f = 0; f < fieldNames.length; f++) {
      var fieldHits = selectWithin(element, config.fields[fieldNames[f]].locator, 'fields.' + fieldNames[f] + '.locator', []);
      fields[fieldNames[f]] = { ok: fieldHits.length === 1, value: fieldHits.length === 1 ? normalizedText(fieldHits[0]).slice(0, 80) : '' };
    }
    var actions = {};
    for (var a = 0; a < actionNames.length; a++) {
      var action = config.actions[actionNames[a]];
      if (action.scope !== 'card') continue;
      var actionHits = selectWithin(element, action.locator, 'actions.' + actionNames[a] + '.locator', []);
      actions[actionNames[a]] = { matches: actionHits.map(function (node) { return normalizedText(node).slice(0, 40); }) };
    }
    // The card's own text, bounded. It is what a semantic judgement reads when a rule cannot
    // be evaluated from the fields alone, and it is evidence rather than a fact: nothing here
    // extracts a value from it.
    cards.push({ identity: identity, text: normalizedText(element).slice(0, 300), fields: fields, actions: actions });
  }

  return {
    url: String(location.href || ''),
    title: String(document.title || ''),
    cards: cards,
    markerFailures: markerFailures,
    unstableConditions: unstableConditions,
  };
}
